name: Build Linux x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dialog editor
        uses: actions/checkout@v4
        with:
          path: dialog-editor

      - name: Checkout daedalus-parser
        uses: actions/checkout@v4
        with:
          repository: daniel-daga/daedalus-parser
          path: daedalus-parser
          ref: main
          token: ${{ secrets.PARSER_REPO_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build daedalus-parser
        working-directory: daedalus-parser
        run: npm ci && npm run build && npm run prebuildify

      - name: Install dependencies
        run: npm ci
        working-directory: dialog-editor

      - name: Build application
        run: npm run build && npm run package
        working-directory: dialog-editor

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64-build
          path: dialog-editor/dist/*.AppImage
          retention-days: 30
