name: Build Linux x64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dialog editor
        uses: actions/checkout@v4

      - name: Checkout daedalus-parser
        uses: actions/checkout@v4
        with:
          repository: daniel-daga/daedalus-parser
          path: ../daedalus-parser

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build daedalus-parser
        working-directory: ../daedalus-parser
        run: npm ci && npm run build && npm run prebuildify

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build && npm run package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64-build
          path: dist/*.AppImage
          retention-days: 30
